name: bot

on:
  schedule:
    - cron: '0 18 * * *'
    - cron: '0 21 * * *'
    - cron: '0 0 * * *'
    - cron: '0 3 * * *'
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: install
        run: pip install -r requirements.txt

      - name: run bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FACEBOOK_PAGE_TOKEN: ${{ secrets.FACEBOOK_PAGE_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
        run: python main.py
